# Generated by Django 2.2.8 on 2020-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defsult.jpg', upload_to='profile_pics'),
        ),
    ]
