# Generated by Django 2.2.8 on 2020-01-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Neighbour', '0003_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
